language: ruby
sudo: true
before_install:
  - sudo apt-get install gnupg
  - gem install bundler
script:
  - bundle exec rake spec
  - bundle exec rake features
rvm:
  - 2.3.1
  - 2.2.5
  - 2.1.9
  - 1.9.3
  - jruby
matrix:
  fast_finish: true
notifications:
  email: false
